"""empty message

Revision ID: 47395f6a030d
Revises: 
Create Date: 2020-04-18 22:18:39.403474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47395f6a030d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
