"""empty message

Revision ID: 4ccd7f8b452e
Revises: 58eb8ad7466a
Create Date: 2020-04-23 06:59:37.709706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccd7f8b452e'
down_revision = '58eb8ad7466a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todolists SET completed=False WHERE completed IS NULL;')
    op.alter_column('todolists', 'completed', nullable=False)
    op.execute('UPDATE todos SET list_id=1 WHERE list_id IS NULL;')
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
